@echo off
REM Batch file to copy SDK Sample DLLs including accelerator DLLs in C#

IF "%GO_SDK_4%" == "" GOTO NOPATH
   :YESPATH
   @ECHO The GO_SDK environment variable was detected.

   xcopy "%GO_SDK_4%\bin\win32\GoSdk.dll" "%CD%\bin\x86\Release\GoSdk.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kApi.dll" "%CD%\bin\x86\Release\kApi.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kApiNet.dll" "%CD%\bin\x86\Release\kApiNet.dll*"
   xcopy "%GO_SDK_4%\bin\win32\GoSdkNet.dll" "%CD%\bin\x86\Release\GoSdkNet.dll*"
   xcopy "%GO_SDK_4%\bin\win32\GoSensor.dll" "%CD%\bin\x86\Release\GoSensor.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kFireSync.dll" "%CD%\bin\x86\Release\kFireSync.dll*"
   xcopy "%GO_SDK_4%\bin\win32\VCRUNTIME140.dll" "%CD%\bin\x86\Release\VCRUNTIME140.dll*"
   xcopy "%GO_SDK_4%\bin\win32\ucrtbase.dll" "%CD%\bin\x86\Release\ucrtbase.dll*"
   xcopy "%GO_SDK_4%\bin\win32\api-ms-win-core-timezone-l1-1-0.dll" "%CD%\bin\x86\Release\api-ms-win-core-timezone-l1-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32\api-ms-win-core-file-l2-1-0.dll" "%CD%\bin\x86\Release\api-ms-win-core-file-l2-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32\api-ms-win-core-localization-l1-2-0.dll" "%CD%\bin\x86\Release\api-ms-win-core-localization-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32\api-ms-win-core-synch-l1-2-0.dll" "%CD%\bin\x86\Release\api-ms-win-core-synch-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32\api-ms-win-core-file-l1-2-0.dll" "%CD%\bin\x86\Release\api-ms-win-core-file-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kVision.dll" "%CD%\bin\x86\Release\kVision.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kFactoryApi.dll" "%CD%\bin\x86\Release\kFactoryApi.dll*"
   xcopy "%GO_SDK_4%\bin\win32\cv100.dll" "%CD%\bin\x86\Release\cv100.dll*"
   xcopy "%GO_SDK_4%\bin\win32\cxcore100.dll" "%CD%\bin\x86\Release\cxcore100.dll*"
   xcopy "%GO_SDK_4%\bin\win32\MSVCP140.dll" "%CD%\bin\x86\Release\MSVCP140.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kServer.dll" "%CD%\bin\x86\Release\kServer.dll*"
   xcopy "%GO_SDK_4%\bin\win32\kHardwareVirtual.dll" "%CD%\bin\x86\Release\kHardwareVirtual.dll*"
   xcopy "%GO_SDK_4%\bin\win32\Gdk.dll" "%CD%\bin\x86\Release\Gdk.dll*"
   xcopy "%GO_SDK_4%\bin\win32\GoVision.dll" "%CD%\bin\x86\Release\GoVision.dll*"
   xcopy "%GO_SDK_4%\bin\win32\GoTools.dll" "%CD%\bin\x86\Release\GoTools.dll*"

   xcopy "%GO_SDK_4%\bin\win32d\GoSdk.dll" "%CD%\bin\x86\Debug\GoSdk.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kApi.dll" "%CD%\bin\x86\Debug\kApi.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kApiNet.dll" "%CD%\bin\x86\Debug\kApiNet.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\GoSdkNet.dll" "%CD%\bin\x86\Debug\GoSdkNet.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\GoSensor.dll" "%CD%\bin\x86\Debug\GoSensor.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kFireSync.dll" "%CD%\bin\x86\Debug\kFireSync.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\VCRUNTIME140D.dll" "%CD%\bin\x86\Debug\VCRUNTIME140D.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\ucrtbased.dll" "%CD%\bin\x86\Debug\ucrtbased.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\api-ms-win-core-timezone-l1-1-0.dll" "%CD%\bin\x86\Debug\api-ms-win-core-timezone-l1-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\api-ms-win-core-file-l2-1-0.dll" "%CD%\bin\x86\Debug\api-ms-win-core-file-l2-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\api-ms-win-core-localization-l1-2-0.dll" "%CD%\bin\x86\Debug\api-ms-win-core-localization-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\api-ms-win-core-synch-l1-2-0.dll" "%CD%\bin\x86\Debug\api-ms-win-core-synch-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\api-ms-win-core-file-l1-2-0.dll" "%CD%\bin\x86\Debug\api-ms-win-core-file-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kVision.dll" "%CD%\bin\x86\Debug\kVision.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kFactoryApi.dll" "%CD%\bin\x86\Debug\kFactoryApi.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\cv100d.dll" "%CD%\bin\x86\Debug\cv100d.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\cxcore100d.dll" "%CD%\bin\x86\Debug\cxcore100d.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\MSVCP140D.dll" "%CD%\bin\x86\Debug\MSVCP140D.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kServer.dll" "%CD%\bin\x86\Debug\kServer.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\kHardwareVirtual.dll" "%CD%\bin\x86\Debug\kHardwareVirtual.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\Gdk.dll" "%CD%\bin\x86\Debug\Gdk.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\GoVision.dll" "%CD%\bin\x86\Debug\GoVision.dll*"
   xcopy "%GO_SDK_4%\bin\win32d\GoTools.dll" "%CD%\bin\x86\Debug\GoTools.dll*"

   xcopy "%GO_SDK_4%\bin\win64\GoSdk.dll" "%CD%\bin\x64\Release\GoSdk.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kApi.dll" "%CD%\bin\x64\Release\kApi.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kApiNet.dll" "%CD%\bin\x64\Release\kApiNet.dll*"
   xcopy "%GO_SDK_4%\bin\win64\GoSdkNet.dll" "%CD%\bin\x64\Release\GoSdkNet.dll*"
   xcopy "%GO_SDK_4%\bin\win64\GoSensor.dll" "%CD%\bin\x64\Release\GoSensor.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kFireSync.dll" "%CD%\bin\x64\Release\kFireSync.dll*"
   xcopy "%GO_SDK_4%\bin\win64\VCRUNTIME140.dll" "%CD%\bin\x64\Release\VCRUNTIME140.dll*"
   xcopy "%GO_SDK_4%\bin\win64\ucrtbase.dll" "%CD%\bin\x64\Release\ucrtbase.dll*"
   xcopy "%GO_SDK_4%\bin\win64\api-ms-win-core-timezone-l1-1-0.dll" "%CD%\bin\x64\Release\api-ms-win-core-timezone-l1-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64\api-ms-win-core-file-l2-1-0.dll" "%CD%\bin\x64\Release\api-ms-win-core-file-l2-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64\api-ms-win-core-localization-l1-2-0.dll" "%CD%\bin\x64\Release\api-ms-win-core-localization-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64\api-ms-win-core-synch-l1-2-0.dll" "%CD%\bin\x64\Release\api-ms-win-core-synch-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64\api-ms-win-core-file-l1-2-0.dll" "%CD%\bin\x64\Release\api-ms-win-core-file-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kVision.dll" "%CD%\bin\x64\Release\kVision.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kFactoryApi.dll" "%CD%\bin\x64\Release\kFactoryApi.dll*"
   xcopy "%GO_SDK_4%\bin\win64\cv100_64.dll" "%CD%\bin\x64\Release\cv100_64.dll*"
   xcopy "%GO_SDK_4%\bin\win64\cxcore100_64.dll" "%CD%\bin\x64\Release\cxcore100_64.dll*"
   xcopy "%GO_SDK_4%\bin\win64\MSVCP140.dll" "%CD%\bin\x64\Release\MSVCP140.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kServer.dll" "%CD%\bin\x64\Release\kServer.dll*"
   xcopy "%GO_SDK_4%\bin\win64\kHardwareVirtual.dll" "%CD%\bin\x64\Release\kHardwareVirtual.dll*"
   xcopy "%GO_SDK_4%\bin\win64\Gdk.dll" "%CD%\bin\x64\Release\Gdk.dll*"
   xcopy "%GO_SDK_4%\bin\win64\GoVision.dll" "%CD%\bin\x64\Release\GoVision.dll*"
   xcopy "%GO_SDK_4%\bin\win64\GoTools.dll" "%CD%\bin\x64\Release\GoTools.dll*"

   xcopy "%GO_SDK_4%\bin\win64d\GoSdk.dll" "%CD%\bin\x64\Debug\GoSdk.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kApi.dll" "%CD%\bin\x64\Debug\kApi.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kApiNet.dll" "%CD%\bin\x64\Debug\kApiNet.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\GoSdkNet.dll" "%CD%\bin\x64\Debug\GoSdkNet.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\GoSensor.dll" "%CD%\bin\x64\Debug\GoSensor.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kFireSync.dll" "%CD%\bin\x64\Debug\kFireSync.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\VCRUNTIME140D.dll" "%CD%\bin\x64\Debug\VCRUNTIME140D.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\ucrtbased.dll" "%CD%\bin\x64\Debug\ucrtbased.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\api-ms-win-core-timezone-l1-1-0.dll" "%CD%\bin\x64\Debug\api-ms-win-core-timezone-l1-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\api-ms-win-core-file-l2-1-0.dll" "%CD%\bin\x64\Debug\api-ms-win-core-file-l2-1-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\api-ms-win-core-localization-l1-2-0.dll" "%CD%\bin\x64\Debug\api-ms-win-core-localization-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\api-ms-win-core-synch-l1-2-0.dll" "%CD%\bin\x64\Debug\api-ms-win-core-synch-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\api-ms-win-core-file-l1-2-0.dll" "%CD%\bin\x64\Debug\api-ms-win-core-file-l1-2-0.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kVision.dll" "%CD%\bin\x64\Debug\kVision.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kFactoryApi.dll" "%CD%\bin\x64\Debug\kFactoryApi.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\cv100d_64.dll" "%CD%\bin\x64\Debug\cv100d_64.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\cxcore100d_64.dll" "%CD%\bin\x64\Debug\cxcore100d_64.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\MSVCP140D.dll" "%CD%\bin\x64\Debug\MSVCP140D.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kServer.dll" "%CD%\bin\x64\Debug\kServer.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\kHardwareVirtual.dll" "%CD%\bin\x64\Debug\kHardwareVirtual.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\Gdk.dll" "%CD%\bin\x64\Debug\Gdk.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\GoVision.dll" "%CD%\bin\x64\Debug\GoVision.dll*"
   xcopy "%GO_SDK_4%\bin\win64d\GoTools.dll" "%CD%\bin\x64\Debug\GoTools.dll*"

   GOTO END
   :NOPATH
   @ECHO The GO_SDK_4 environment variable was NOT detected.Please set the ENV Variable GO_SDK_4 to point to the Go SDK Directory.
   GOTO END
   :END

pause